[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi=true  #this means that you are going to let foundry run commands directly on your machine
# See more config options https://github.com/foundry-rs/foundry/tree/master/config